### ISSUE TITLE
How can I tidy data without it taking inordinate amounts of time?

### ISSUE THREAD

**Issue by jacolb22** [jacolb22/lab-05#1]
When I wrote my initial code to go through each file, and just print out the lines, it didn't finish in 5 minutes, before I stopped it. How then, should I approach going through all of it and adding it to a string vector. Additionally, how can I get rid of the header file without rewriting the read_file functionality myself? 

My thought process is described below:

go through every file
get lines below header
add them to a string vector, perhaps add another two vectors for file number and line number
make that a tibble

@francojc

**Comment by jacolb22** [comment]
Figured it out, hopefully my implementation is what is intended by the instructions.

**Comment by francojc** [comment]
Glad to hear you addressed this. Yes, outputting data to the console is not recommended. This is one reason we use tibbles instead of regular data frames to avoid accidentally doing this when we are inspecting data.

**Comment by jacolb22** [comment]
Okay, good to know. I never knew print() was so slow.

**Comment by francojc** [comment]
Well when there are half a million rows with a good amount of data in each of the cells, it can take a while. 🫤
